version: '2.1'
services:
  latest:
    image: "linshenqi/notifly"
    ports:
      - "10002:10002"
    volumes:
      - /data/res:/etc/notifly/res
      - /data/notifly/conf:/etc/notifly/conf
      - /data/notifly/log:/etc/notifly/log
      - /etc/localtime:/etc/localtime:ro
    restart: "always"
#    healthcheck:
#      test: curl -f --silent --fail http://127.0.0.1:8082/api/v1/healthz || exit 1
#      interval: 5s
#      timeout: 3s
#      retries: 3
