version: '2.1'
services:
  latest:
    image: "linshenqi/notify"
    ports:
      - "10002:10002"
    volumes:
      - /data/notify/conf:/etc/notify/conf
      - /data/notify/log:/etc/notify/log
      - /etc/localtime:/etc/localtime:ro
    restart: "always"
#    healthcheck:
#      test: curl -f --silent --fail http://127.0.0.1:8082/api/v1/healthz || exit 1
#      interval: 5s
#      timeout: 3s
#      retries: 3
