version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build docker image
          command: |
            mkdir -p /go/src/github.com/linshenqi/notifly && cd /go/src/github.com/linshenqi/notifly
            cp -r /home/circleci/project/* ./
            ls -al ./
            #go get -u github.com/golang/dep
            #dep ensure -v
            CGO_ENABLED=0 go build -o ./build/notifly ./src/main.go
            docker login -u $DOCKER_USER -p $DOCKER_PWD
            sh ./build_docker.sh
