
log:
  file: STDOUT
  level: DEBUG
  max_age: 1000h
  rotate: 24h

http:
  addr: :10002

wechat:
  respath: /home/linshenqi/Pictures
  endpoints:
    mp:
      app_id: wx919dfd3bc27aca6b
      app_secret: 4c2516457b0b6fffabf9623f97dbb490
    srv:
      app_id: wx8932920e57b26e36
      app_secret: a80b2a0fd151ebf647590ad93414e129
    enterprise:
      app_id: ww0156ea32144ac4fc
      app_secret: na

sms:
  endpoints:
    ashibro_cn:
      provider: aliyun
      app_key: 123
      app_secret: 123
      region: cn-hangzhou
      sign_name: Ashibro
      template_code: 123
    ashibro:
      provider: twilio
      app_key: 123
      app_secret: 123
      host_num: +1123124124

email:
  endpoints:
    ashibro:
      author: wef@wef.com
      pwd: 3234
      host: smtp.wef.com
      port: 123
